/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Temperature = IDL.Nat;
export const Hours = IDL.Nat;
export const ACUnit = IDL.Record({
  'id' : IDL.Nat,
  'temperature' : Temperature,
  'mode' : IDL.Text,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'sleepMode' : IDL.Bool,
  'fanSpeed' : IDL.Text,
  'timerOnHours' : IDL.Opt(Hours),
  'power' : IDL.Bool,
  'timerOffHours' : IDL.Opt(Hours),
});
export const ACUnitInput = IDL.Record({
  'temperature' : Temperature,
  'mode' : IDL.Text,
  'name' : IDL.Text,
  'sleepMode' : IDL.Bool,
  'fanSpeed' : IDL.Text,
  'power' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addUnit' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getAllUnits' : IDL.Func([], [IDL.Vec(ACUnit)], ['query']),
  'getUnit' : IDL.Func([IDL.Nat], [ACUnit], ['query']),
  'removeUnit' : IDL.Func([IDL.Nat], [], []),
  'renameUnit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setTimers' : IDL.Func([IDL.Nat, IDL.Opt(Hours), IDL.Opt(Hours)], [], []),
  'toggleOnlineStatus' : IDL.Func([IDL.Nat], [], []),
  'updateUnit' : IDL.Func([IDL.Nat, ACUnitInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Temperature = IDL.Nat;
  const Hours = IDL.Nat;
  const ACUnit = IDL.Record({
    'id' : IDL.Nat,
    'temperature' : Temperature,
    'mode' : IDL.Text,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'sleepMode' : IDL.Bool,
    'fanSpeed' : IDL.Text,
    'timerOnHours' : IDL.Opt(Hours),
    'power' : IDL.Bool,
    'timerOffHours' : IDL.Opt(Hours),
  });
  const ACUnitInput = IDL.Record({
    'temperature' : Temperature,
    'mode' : IDL.Text,
    'name' : IDL.Text,
    'sleepMode' : IDL.Bool,
    'fanSpeed' : IDL.Text,
    'power' : IDL.Bool,
  });
  
  return IDL.Service({
    'addUnit' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getAllUnits' : IDL.Func([], [IDL.Vec(ACUnit)], ['query']),
    'getUnit' : IDL.Func([IDL.Nat], [ACUnit], ['query']),
    'removeUnit' : IDL.Func([IDL.Nat], [], []),
    'renameUnit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setTimers' : IDL.Func([IDL.Nat, IDL.Opt(Hours), IDL.Opt(Hours)], [], []),
    'toggleOnlineStatus' : IDL.Func([IDL.Nat], [], []),
    'updateUnit' : IDL.Func([IDL.Nat, ACUnitInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };