/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ACUnitInput {
    temperature: Temperature;
    mode: string;
    name: string;
    sleepMode: boolean;
    fanSpeed: string;
    power: boolean;
}
export interface ACUnit {
    id: bigint;
    temperature: Temperature;
    mode: string;
    name: string;
    isOnline: boolean;
    sleepMode: boolean;
    fanSpeed: string;
    timerOnHours?: Hours;
    power: boolean;
    timerOffHours?: Hours;
}
export type Temperature = bigint;
export type Hours = bigint;
export interface backendInterface {
    addUnit(name: string): Promise<bigint>;
    getAllUnits(): Promise<Array<ACUnit>>;
    getUnit(id: bigint): Promise<ACUnit>;
    removeUnit(id: bigint): Promise<void>;
    renameUnit(id: bigint, newName: string): Promise<void>;
    setTimers(id: bigint, onHours: Hours | null, offHours: Hours | null): Promise<void>;
    toggleOnlineStatus(id: bigint): Promise<void>;
    updateUnit(id: bigint, input: ACUnitInput): Promise<void>;
}
import type { ACUnit as _ACUnit, Hours as _Hours, Temperature as _Temperature } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addUnit(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addUnit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUnit(arg0);
            return result;
        }
    }
    async getAllUnits(): Promise<Array<ACUnit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUnits();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUnits();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnit(arg0: bigint): Promise<ACUnit> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnit(arg0);
                return from_candid_ACUnit_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnit(arg0);
            return from_candid_ACUnit_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeUnit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUnit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUnit(arg0);
            return result;
        }
    }
    async renameUnit(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameUnit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameUnit(arg0, arg1);
            return result;
        }
    }
    async setTimers(arg0: bigint, arg1: Hours | null, arg2: Hours | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTimers(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTimers(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async toggleOnlineStatus(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleOnlineStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleOnlineStatus(arg0);
            return result;
        }
    }
    async updateUnit(arg0: bigint, arg1: ACUnitInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUnit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUnit(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ACUnit_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ACUnit): ACUnit {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Hours]): Hours | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    temperature: _Temperature;
    mode: string;
    name: string;
    isOnline: boolean;
    sleepMode: boolean;
    fanSpeed: string;
    timerOnHours: [] | [_Hours];
    power: boolean;
    timerOffHours: [] | [_Hours];
}): {
    id: bigint;
    temperature: Temperature;
    mode: string;
    name: string;
    isOnline: boolean;
    sleepMode: boolean;
    fanSpeed: string;
    timerOnHours?: Hours;
    power: boolean;
    timerOffHours?: Hours;
} {
    return {
        id: value.id,
        temperature: value.temperature,
        mode: value.mode,
        name: value.name,
        isOnline: value.isOnline,
        sleepMode: value.sleepMode,
        fanSpeed: value.fanSpeed,
        timerOnHours: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.timerOnHours)),
        power: value.power,
        timerOffHours: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.timerOffHours))
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ACUnit>): Array<ACUnit> {
    return value.map((x)=>from_candid_ACUnit_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Hours | null): [] | [_Hours] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
